// lib/sampleJobs.ts
import type { Job } from "./types";

export const JOBS: Job[] = [
  {
    id: "greenhouse:js-qr",
    firm: "Jane Street",
    tier: "SSS",
    title: "Quantitative Researcher",
    role: "Researcher",
    location: "New York, NY",
    locationGroup: "NYC",
    workMode: "On-site",
    languages: ["OCaml", "Python"],
    skills: ["Statistical Arbitrage", "Machine Learning"],
    compRange: "$400k–$600k+",
    postedAt: "2026-05-29T08:30:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Design and test trading strategies across global markets. Strong probability and statistics background; OCaml exposure a plus.",
    description: "As a Quantitative Researcher at Jane Street, you will sit at the intersection of mathematical theory, programming, and real-time market action. You will work on pricing and trading models that process billions in transactions daily. \n\nWhat you will do:\n- Source, clean, and model alternative datasets for alpha generation.\n- Design and backtest statistical arbitrage strategies.\n- Partner with Core Software Developers to write high-performance production code.\n\nQualifications:\n- PhD or Master's in Math, Statistics, Physics, or Computer Science.\n- Solid python coding skills for research; OCaml exposure is a huge plus.\n- Intuitive grasp of probability, stochastic processes, and linear algebra.",
    applyUrl: "https://www.janestreet.com/join-jane-street/"
  },
  {
    id: "greenhouse:citsec-qt",
    firm: "Citadel Securities",
    tier: "SSS",
    title: "Quantitative Trader — Equities",
    role: "Trader",
    location: "New York, NY",
    locationGroup: "NYC",
    workMode: "On-site",
    languages: ["Python", "C++"],
    skills: ["Statistical Arbitrage"],
    compRange: "$350k–$550k+",
    postedAt: "2026-05-30T14:15:00.000Z",
    scrapedAt: "2026-05-30T18:00:00.000Z",
    source: "greenhouse",
    snippet: "Own intraday risk on a systematic equities pod. Comfortable with statistical arbitrage and live PnL ownership.",
    description: "Citadel Securities is looking for an exceptional Quantitative Trader to manage portfolios and own risk within our Equities division.\n\nResponsibilities:\n- Manage day-to-day risk of mid-to-high-frequency systematic equity portfolios.\n- Monitor execution algorithms, transaction cost analysis (TCA), and market microstructure metrics.\n- Continuously refine existing signals and parameters using historical data.\n\nRequirements:\n- 2+ years of experience trading live systematic portfolios.\n- Strong fluency in Python and/or C++.\n- Demonstrated track record of managing risk and delivering consistent Sharpe ratio.",
    applyUrl: "https://www.citadelsecurities.com/careers/"
  },
  {
    id: "lever:hrt-dev",
    firm: "Hudson River Trading",
    tier: "SS",
    title: "Core Quant Developer (C++)",
    role: "Developer",
    location: "Chicago, IL",
    locationGroup: "Chicago",
    workMode: "On-site",
    languages: ["C++", "Python"],
    skills: ["Low Latency"],
    compRange: "$300k–$475k",
    postedAt: "2026-05-28T09:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "lever",
    snippet: "Build and optimize low-latency trading infrastructure. Deep C++ and systems-level performance tuning required.",
    description: "At Hudson River Trading, we build automated trading systems running on high-speed hardware globally. We are seeking a Core Quant Developer to push the boundaries of C++ low-latency optimization.\n\nWhat you'll work on:\n- Optimize our order routing and market data feed handlers down to the sub-microsecond level.\n- Leverage modern C++ features (C++20/23) and hardware-level constructs (cache lines, lock-free queues, kernel bypass).\n- Build simulations and compiler setups for backtesting.\n\nSkills Needed:\n- Expert-level modern C++ design patterns and systems optimization.\n- Strong Linux systems internals knowledge (network stack, scheduling, assembly diagnostics).\n- Familiarity with Python for testing frameworks.",
    applyUrl: "https://www.hudsonrivertrading.com/careers/"
  },
  {
    id: "greenhouse:opt-qt",
    firm: "Optiver",
    tier: "SS",
    title: "Quantitative Trader — Options",
    role: "Trader",
    location: "London, UK",
    locationGroup: "London",
    workMode: "On-site",
    languages: ["Python"],
    skills: ["Market Making"],
    compRange: "£120k–£250k",
    postedAt: "2026-05-27T10:45:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Make markets in listed derivatives. Fast mental math and strong intuition for pricing and risk under pressure.",
    description: "Optiver is a leading global market maker. As an Options Trader in London, you will provide liquidity to financial markets under challenging conditions.\n\nYour profile:\n- Fast mental arithmetic and strong probability intuition.\n- Decisiveness and composure when pricing under stress.\n- Familiarity with derivatives pricing and python scripting.\n\nWe provide a world-class training program to learn options theory, risk management, and simulator-based trading.",
    applyUrl: "https://www.optiver.com/working-at-optiver/career-opportunities/"
  },
  {
    id: "greenhouse:2s-ds",
    firm: "Two Sigma",
    tier: "SS",
    title: "Data Scientist — Alpha Research",
    role: "Data Scientist",
    location: "New York, NY",
    locationGroup: "NYC",
    workMode: "Hybrid",
    languages: ["Python"],
    skills: ["Machine Learning"],
    compRange: "$250k–$400k",
    postedAt: "2026-05-26T16:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Source and validate alternative datasets, build features, and prototype models for systematic strategies.",
    description: "Two Sigma is a technology-driven asset manager. We are seeking a Data Scientist to join our Alpha Research division.\n\nKey Responsibilities:\n- Process, structure, and model messy alternative data sources (satellite images, credit card logs, text feeds).\n- Build predictive features and validate them via rigorous statistical backtesting.\n- Build and train machine learning models (XGBoost, neural networks) to forecast asset movements.\n\nRequirements:\n- PhD or MS with 2+ years of experience in data analysis.\n- Expert in Python data stack (pandas, numpy, scikit-learn).\n- Deep statistical foundation (cross-validation, hypothesis testing, overfitting prevention).",
    applyUrl: "https://www.twosigma.com/careers/"
  },
  {
    id: "greenhouse:cit-ds",
    firm: "Citadel",
    tier: "S",
    title: "ML Data Scientist",
    role: "Data Scientist",
    location: "Chicago, IL",
    locationGroup: "Chicago",
    workMode: "On-site",
    languages: ["Python"],
    skills: ["Machine Learning", "Low Latency"],
    compRange: "$220k–$360k",
    postedAt: "2026-05-24T11:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Apply machine learning to execution and microstructure problems. Strong applied ML and feature engineering.",
    description: "Citadel's Quantitative Research team is looking for a Machine Learning Data Scientist in Chicago to optimize trade execution algorithms and market impact models.\n\nKey Areas:\n- Model order book dynamics, queue positioning, and routing optimization.\n- Train reinforcement learning or deep neural nets on tick-by-tick order book data.\n- Feature extraction from massive trade logs.\n\nQualifications:\n- Strong background in machine learning and mathematical modeling.\n- Proficient in Python; experience with high-performance C++ is highly valued.\n- Deep understanding of optimization and neural architectures.",
    applyUrl: "https://www.citadel.com/careers/"
  },
  {
    id: "ashby:jt-dev",
    firm: "Jump Trading",
    tier: "SS",
    title: "Quantitative Developer — Rust/C++",
    role: "Developer",
    location: "Singapore",
    locationGroup: "Singapore",
    workMode: "On-site",
    languages: ["C++", "Rust", "Python"],
    skills: ["Low Latency"],
    compRange: "$280k–$420k+",
    postedAt: "2026-05-29T15:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "ashby",
    snippet: "Expand high-frequency Asian market access. Optimize connectivity handlers and algorithmic logic in C++/Rust.",
    description: "Jump Trading is a global research-driven trading group. We are expanding our Singapore team and looking for a Quant Developer fluent in modern low-latency environments.\n\nResponsibilities:\n- Design high-speed execution engines in Rust and C++ for Asian exchanges.\n- Build backtesting simulators and research data parsers.\n- Optimize connectivity code down to the nanosecond level.\n\nRequirements:\n- 3+ years experience with Rust or modern C++.\n- Familiarity with network protocols (TCP/IP, UDP, FIX, binary exchange feeds).\n- Strong interest in high-frequency trading microstructure.",
    applyUrl: "https://www.jumptrading.com/careers/"
  },
  {
    id: "greenhouse:p72-qr",
    firm: "Point72",
    tier: "SS",
    title: "Quantitative Researcher — Stat Arb",
    role: "Researcher",
    location: "New York, NY",
    locationGroup: "NYC",
    workMode: "Hybrid",
    languages: ["Python"],
    skills: ["Statistical Arbitrage", "Machine Learning"],
    compRange: "$320k–$500k",
    postedAt: "2026-05-28T14:30:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Formulate statistical models to trade mid-frequency equities. Implement machine learning features for alphas.",
    description: "Point72's Cubist Systematic Strategies is looking for a Quantitative Researcher to develop mid-frequency statistical arbitrage alphas for equities.\n\nKey Activities:\n- Build predictive mathematical models using fundamental, technical, and alternative data.\n- Apply ML modeling techniques to forecast price action over horizons from days to weeks.\n- Allocate portfolio risk and optimize trading costs.\n\nRequirements:\n- PhD in a quantitative field from a top university.\n- Solid Python programming skills; knowledge of statistical packages.\n- Creative signal generation capabilities and rigour in scientific testing.",
    applyUrl: "https://www.point72.com/careers/"
  },
  {
    id: "lever:bam-qt",
    firm: "Balyasny",
    tier: "S",
    title: "Systematic Trader — Futures/FX",
    role: "Trader",
    location: "London, UK",
    locationGroup: "London",
    workMode: "Hybrid",
    languages: ["Python"],
    skills: ["Market Making"],
    compRange: "£150k–£300k+",
    postedAt: "2026-05-25T09:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "lever",
    snippet: "Execute systematic macro models across liquid global futures and FX markets. Monitor execution and risk.",
    description: "Balyasny Asset Management is seeking a Systematic Trader for our Macro trading desk in London.\n\nKey Roles:\n- Oversee execution of systematic models across futures and G10 FX currencies.\n- Troubleshoot execution logs and adjust limits during periods of extreme volatility.\n- Analyze trade slippage and collaborate with researchers to improve performance.\n\nRequirements:\n- Broad knowledge of macro markets (Rates, FX, Commodities).\n- 2+ years of systematic trading desk experience.\n- Fluent in Python for data querying and automated reports.",
    applyUrl: "https://www.bamfunds.com/careers"
  },
  {
    id: "greenhouse:trc-swe",
    firm: "Tower Research",
    tier: "SS",
    title: "HFT Software Engineer (C++)",
    role: "Developer",
    location: "New York, NY",
    locationGroup: "NYC",
    workMode: "On-site",
    languages: ["C++"],
    skills: ["Low Latency"],
    compRange: "$290k–$440k",
    postedAt: "2026-05-29T10:00:00.000Z",
    scrapedAt: "2026-05-30T11:00:00.000Z",
    source: "greenhouse",
    snippet: "Maintain ultra-low-latency market gateways. Profile code, resolve CPU bottlenecks, and use kernel bypass.",
    description: "Tower Research Capital is a leading electronic trading firm. We are looking for a C++ HFT Software Engineer to work on our core exchange gateways in New York.\n\nWhat you will do:\n- Build and maintain exchange connectivity layers for NASDAQ, NYSE, CME, etc.\n- Profile production performance using Linux profiling tools (perf, VTune).\n- Implement custom network stacks utilizing Solarflare EF_VI and kernel bypass (DPDK).\n\nRequirements:\n- Expert-level understanding of C++ (C++20).\n- Proficient in Linux system programming, multi-threading, and CPU affinity.\n- High interest in low-level compiler optimization and hardware-software interaction.",
    applyUrl: "https://www.tower-research.com/careers"
  },
  {
    id: "lever:drw-ml",
    firm: "DRW",
    tier: "S",
    title: "Quantitative Researcher — ML",
    role: "Researcher",
    location: "Chicago, IL",
    locationGroup: "Chicago",
    workMode: "Hybrid",
    languages: ["Python", "Rust"],
    skills: ["Machine Learning"],
    compRange: "$200k–$320k",
    postedAt: "2026-05-23T13:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "lever",
    snippet: "Apply deep learning and NLP to sentiment indicators and macro forecasting. Familiarity with PyTorch.",
    description: "DRW is a principal trading firm. We are seeking a Machine Learning Quant Researcher in Chicago to build next-generation NLP and forecasting systems.\n\nResponsibilities:\n- Train transformers and LLMs on news wires, transcripts, and financial documents to extract sentiment alphas.\n- Build robust ML architectures for timeseries forecasting.\n- Leverage PyTorch and distributed GPU clusters.\n\nQualifications:\n- PhD or MS in computer science, machine learning, or stats.\n- 2+ years utilizing deep learning and NLP in finance or tech.\n- Solid engineering background in Python and Rust.",
    applyUrl: "https://www.drw.com/careers"
  },
  {
    id: "ashby:mly-qd",
    firm: "Millennium",
    tier: "SS",
    title: "Quantitative Developer — Equities",
    role: "Developer",
    location: "Singapore",
    locationGroup: "Singapore",
    workMode: "On-site",
    languages: ["C++", "Python"],
    skills: ["Statistical Arbitrage"],
    compRange: "$270k–$430k",
    postedAt: "2026-05-28T07:15:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "ashby",
    snippet: "Integrate equities alpha signals into trading engines. Build real-time risk calculators and signal backtesters.",
    description: "Millennium is a premier global alternative investment manager. We are seeking a Quantitative Developer to join a successful Equities Systematic pod in Singapore.\n\nRoles:\n- Build real-time risk and pricing calculators for systematic equity strategies.\n- Write wrappers and bindings to load alpha signals written in Python into our C++ execution engine.\n- Optimize portfolio rebalancing logic.\n\nRequired Skills:\n- Strong programming skills in both C++ and Python.\n- Understanding of statistical arbitrage, optimization, or risk modeling.\n- Exceptional problem-solving skills.",
    applyUrl: "https://www.mlm.com/careers"
  },
  {
    id: "greenhouse:gr-ds",
    firm: "G-Research",
    tier: "S",
    title: "Quantitative Data Scientist",
    role: "Data Scientist",
    location: "London, UK",
    locationGroup: "London",
    workMode: "Hybrid",
    languages: ["Python"],
    skills: ["Machine Learning"],
    compRange: "£110k–£210k",
    postedAt: "2026-05-22T08:00:00.000Z",
    scrapedAt: "2026-05-30T10:00:00.000Z",
    source: "greenhouse",
    snippet: "Extract signals from structured financial data. Perform statistical regression, predictive modeling, and feature testing.",
    description: "G-Research is Europe's leading quantitative research and technology firm. We are looking for Data Scientists in London to predict future movements in global markets.\n\nYour Work:\n- Run machine learning models and regressions on large arrays of market data.\n- Build features and evaluate statistical significance.\n- Collaborate in a research-focused environment with state-of-the-art compute resources.\n\nKey skills:\n- Strong coding in Python and analytical frameworks (numpy, pandas, tensorflow).\n- Solid background in mathematical statistics, linear algebra, and data science.",
    applyUrl: "https://www.gresearch.co.uk/careers"
  },
  {
    id: "custom:qrt-qr",
    firm: "Qube Research & Technologies",
    tier: "SS",
    title: "Quantitative Researcher",
    role: "Researcher",
    location: "Singapore",
    locationGroup: "Singapore",
    workMode: "On-site",
    languages: ["Python", "C++"],
    skills: ["Statistical Arbitrage", "Machine Learning"],
    compRange: "$300k–$480k+",
    postedAt: "2026-05-29T11:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Develop quantitative trading strategies across liquid asset classes. Strong math, machine learning, and python background.",
    description: "Qube Research & Technologies (QRT) is a global quantitative investment manager. We are seeking a Quantitative Researcher to join our rapidly growing Singapore office.\n\nKey Responsibilities:\n- Research and design systematic alpha signals for global equities and futures.\n- Apply machine learning models to massive alternative and market data streams.\n- Continuously backtest and refine execution parameters to optimize transaction costs.\n\nRequirements:\n- PhD or MS in math, statistics, computer science, or a highly quantitative discipline.\n- Solid programming skills in Python; C++ experience is highly valued.\n- Deep understanding of linear models, optimization, and time series analysis.",
    applyUrl: "https://www.qube-rt.com/"
  },
  {
    id: "custom:imc-qd",
    firm: "IMC Trading",
    tier: "SS",
    title: "Quantitative Developer — Execution",
    role: "Developer",
    location: "Singapore",
    locationGroup: "Singapore",
    workMode: "On-site",
    languages: ["C++", "Python"],
    skills: ["Low Latency"],
    compRange: "$260k–$400k+",
    postedAt: "2026-05-28T10:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Optimize high-frequency execution algorithms and low-latency exchange interfaces in C++. Singapore office.",
    description: "IMC Trading is a leading global market maker. We are seeking a Quantitative Developer to build and optimize low-latency trading infrastructure in our Singapore team.\n\nResponsibilities:\n- Design, develop, and maintain high-performance execution software in modern C++.\n- Profile and optimize hot paths down to sub-microsecond latency.\n- Collaborate with options and delta-one traders to implement electronic strategies.\n\nRequirements:\n- 2+ years of software development experience in modern C++ (C++17/20).\n- Strong systems foundations: network sockets, threading, locks, memory layouts.\n- Experience with high-speed exchange feed protocols is a plus.",
    applyUrl: "https://www.imc.com/careers/"
  },
  {
    id: "custom:sig-qt",
    firm: "Susquehanna (SIG)",
    tier: "SS",
    title: "Quantitative Trader",
    role: "Trader",
    location: "Sydney, Australia",
    locationGroup: "Sydney",
    workMode: "On-site",
    languages: ["Python"],
    skills: ["Market Making"],
    compRange: "$240k–$380k+",
    postedAt: "2026-05-27T08:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Trade derivatives and manage pricing algorithms in a fast-paced environment. Strong options theory required.",
    description: "Susquehanna International Group (SIG) is a global proprietary trading firm. We are looking for a Quantitative Trader to join our options desk in Sydney.\n\nWhat you will do:\n- Price and trade complex financial instruments (primarily options and derivatives).\n- Monitor and adjust trading parameters using systematic valuation models.\n- Partner with researchers and developers to refine automated strategy execution.\n\nRequirements:\n- Outstanding mathematical skills and probability intuition.\n- Decisiveness and composure to react to market events under pressure.\n- Strong interest in financial markets; coding in Python is highly valued.",
    applyUrl: "https://sig.com/careers/"
  },
  {
    id: "custom:qrt-in-swe",
    firm: "Qube Research & Technologies",
    tier: "SS",
    title: "Quant Systems Engineer",
    role: "Developer",
    location: "Gurugram, India",
    locationGroup: "Gurugram",
    workMode: "On-site",
    languages: ["C++", "Python", "Rust"],
    skills: ["Low Latency"],
    compRange: "₹4,000,000–₹7,000,000",
    postedAt: "2026-05-29T14:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Build high-throughput data pipelines and optimization tools for systematic trading. Gurugram office.",
    description: "Qube Research & Technologies (QRT) is expanding its engineering presence in India. We are seeking a Quant Systems Engineer to build high-performance data systems and backtest clusters in Gurugram.\n\nKey Activities:\n- Construct robust, parallel pipelines to process terabytes of tick data daily.\n- Develop tooling in C++ and Rust to accelerate alpha research backtests.\n- Optimize database queries and cloud infrastructure to ensure microsecond-level access.\n\nRequirements:\n- BTech/MTech in Computer Science from a premier institution (IIT/BITS/NIT).\n- Proficient in C++ or Rust, with strong Python scripting foundations.\n- Excellent grasp of data structures, operating systems, and database internals.",
    applyUrl: "https://www.qube-rt.com/"
  },
  {
    id: "custom:nk-qr",
    firm: "NK Securities",
    tier: "S",
    title: "Quantitative Researcher",
    role: "Researcher",
    location: "Gurugram, India",
    locationGroup: "Gurugram",
    workMode: "On-site",
    languages: ["Python", "C++"],
    skills: ["Statistical Arbitrage", "Machine Learning"],
    compRange: "₹5,000,000–₹8,000,000+",
    postedAt: "2026-05-30T10:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Design and implement high-frequency trading strategies on Indian and global exchanges.",
    description: "NK Securities Research is a leading global proprietary trading firm. We are looking for Quantitative Researchers to join our team in Gurugram.\n\nKey Responsibilities:\n- Develop and implement high-frequency trading strategies.\n- Analyze market microstructure and order book dynamics.\n- Build predictive mathematical models using advanced statistical techniques.",
    applyUrl: "https://www.nksecurities.com/careers"
  },
  {
    id: "custom:graviton-ml",
    firm: "Graviton Research Capital",
    tier: "SS",
    title: "Machine Learning Researcher",
    role: "Researcher",
    location: "Gurugram, India",
    locationGroup: "Gurugram",
    workMode: "On-site",
    languages: ["Python", "C++"],
    skills: ["Machine Learning", "Statistical Arbitrage"],
    compRange: "₹8,000,000–₹12,000,000+",
    postedAt: "2026-05-30T11:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Apply deep learning and machine learning algorithms to high-frequency market data in Gurugram.",
    description: "Graviton Research Capital is a premier quantitative trading firm. We are seeking an exceptional ML Researcher to join our team in India.\n\nRole:\n- Apply modern deep learning and machine learning to large financial datasets.\n- Research and design state-of-the-art predictive signals.\n- Partner with developers to optimize performance for sub-microsecond execution.",
    applyUrl: "https://www.graviton.co.in/"
  },
  {
    id: "custom:alphagrep-qt",
    firm: "AlphaGrep",
    tier: "S",
    title: "Quantitative Trader",
    role: "Trader",
    location: "Gurugram, India",
    locationGroup: "Gurugram",
    workMode: "On-site",
    languages: ["Python"],
    skills: ["Market Making", "Statistical Arbitrage"],
    compRange: "₹6,000,000–₹10,000,000+",
    postedAt: "2026-05-29T09:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Manage and optimize algorithmic trading strategies on Indian and global exchanges.",
    description: "AlphaGrep is a quantitative proprietary trading firm. We are seeking a Quantitative Trader to run systematic models and optimize risk.\n\nQualifications:\n- 2+ years of trading experience in liquid futures or equities.\n- Strong quantitative reasoning and math foundations.\n- Basic coding skills in Python for data analysis.",
    applyUrl: "https://alpha-grep.com/careers"
  },
  {
    id: "custom:aqr-qa",
    firm: "AQR Capital Management",
    tier: "S",
    title: "Quantitative Research Analyst",
    role: "Researcher",
    location: "Greenwich, CT",
    locationGroup: "Other",
    workMode: "Hybrid",
    languages: ["Python", "C++"],
    skills: ["Statistical Arbitrage"],
    compRange: "$180,000–$260,000",
    postedAt: "2026-05-28T09:00:00.000Z",
    scrapedAt: "2026-05-30T12:00:00.000Z",
    source: "custom",
    snippet: "Develop systematic equity and macro investment models for global hedge fund portfolios.",
    description: "AQR is a global investment management firm. We are seeking a Quant Analyst to join our Systematic Equities team in Greenwich, CT.\n\nResponsibilities:\n- Design and backtest long-horizon equity alpha signals.\n- Research alternative data sources and ESG indicators.\n- Maintain and optimize production portfolio construction code.",
    applyUrl: "https://www.aqr.com/About-Us/Careers"
  },
  {
    id: "custom:deshaw-dev",
    firm: "D.E. Shaw (DESHAW)",
    tier: "SS",
    title: "Core Quant Developer",
    role: "Developer",
    location: "Gurugram, India",
    locationGroup: "Gurugram",
    workMode: "Hybrid",
    languages: ["Python", "C++"],
    skills: ["Low Latency"],
    compRange: "₹5,000,000–₹9,000,000",
    postedAt: "2026-05-30T14:00:00.000Z",
    scrapedAt: "2026-05-30T15:00:00.000Z",
    source: "custom",
    snippet: "Build high-performance computing clusters and systematic simulation infrastructure in Gurugram.",
    description: "The D.E. Shaw Group is a trusted global investment pioneer. We are looking for a Core Quant Developer for our systematic trading teams in Hyderabad/Gurugram.\n\nKey Skills:\n- Strong knowledge of Linux systems programming and modern C++.\n- Experience in building highly scalable, distributed research clusters.\n- Experience with high-performance Python libraries.",
    applyUrl: "https://www.deshaw.com/careers"
  },
  {
    id: "custom:jpmc-qr",
    firm: "JPMorgan Chase (JPMC)",
    tier: "S",
    title: "Quantitative Research Associate (IB)",
    role: "Researcher",
    location: "Mumbai, India",
    locationGroup: "Other",
    workMode: "Hybrid",
    languages: ["Python", "C++"],
    skills: ["Market Making"],
    compRange: "₹3,500,000–₹5,500,000",
    postedAt: "2026-05-29T12:00:00.000Z",
    scrapedAt: "2026-05-30T15:00:00.000Z",
    source: "custom",
    snippet: "Develop derivative pricing models and systematic hedging algorithms for global markets.",
    description: "J.P. Morgan is a global leader in financial services. Our Quantitative Research team in Mumbai is looking for an Associate to support the Fixed Income derivatives desk.\n\nRole:\n- Implement quantitative valuation models for derivatives.\n- Code pricing modules in C++ and Python.\n- Design automated risk reporting and hedging scripts.",
    applyUrl: "https://careers.jpmorgan.com/US/en/home"
  },
  {
    id: "custom:gs-strat",
    firm: "Goldman Sachs (GS)",
    tier: "S",
    title: "Quantitative Strategist (Strats)",
    role: "Developer",
    location: "Bengaluru, India",
    locationGroup: "Other",
    workMode: "On-site",
    languages: ["C++", "Python"],
    skills: ["Low Latency"],
    compRange: "₹3,000,000–₹5,000,000",
    postedAt: "2026-05-28T10:00:00.000Z",
    scrapedAt: "2026-05-30T15:00:00.000Z",
    source: "custom",
    snippet: "Build algorithmic execution models and electronic trading logic for equities franchises.",
    description: "Goldman Sachs is a leading global financial institution. We are seeking a Strats professional in Bengaluru to support our algorithmic execution platforms.\n\nResponsibilities:\n- Design client execution algorithms and transaction cost analysis (TCA) frameworks.\n- Optimize performance of electronic trading workflows in C++ and Java.\n- Build tools for systematic market impact research.",
    applyUrl: "https://www.goldmansachs.com/careers/"
  }
];
